version: "3"
services:
  jekyll:
    command: jekyll serve -s jekyll --incremental --livereload
    image: jekyll/jekyll:3.8.5
    volumes:
      - ".:/srv/jekyll"
    ports:
      - 4000:4000
      - 35729:35729
